# Generated by Django 5.1.3 on 2024-12-19 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ipl',
            fields=[
                ('sl_no', models.DecimalField(decimal_places=2, max_digits=5, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4, unique=True)),
                ('winner', models.CharField(choices=[('win', 'Win'), ('lose', 'Lose')], default='lose', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50, unique=True)),
                ('position', models.DecimalField(decimal_places=0, max_digits=2)),
                ('ipl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ipl')),
            ],
        ),
    ]
